### ISSUE TITLE
Renaming the extension ts to js

### ISSUE THREAD

**Issue by moshOntong-IT** [JohnBra/vite-web-extension#1]
So I have to change the extension file of my content.ts to content js. The problem is, when I build my project the index js in dist/src/page/content is empty

**Comment by moshOntong-IT** [comment]
I solved it, I just forget to call the function

**Comment by JohnBra** [comment]
> So I have to change the extension file of my content.ts to content js. The problem is, when I build my project the index js in dist/src/page/content is empty

Hi,

From what you have written it sounds like you added a file named 'content.ts'. Make sure you also have 'index.ts' as provided in the template and import/implement your logic there.

If that doesn't help, please provide a minimal reproduction of your issue, so I can look into it.
