### ISSUE TITLE
Default template applies CSS reset to any visited page

### ISSUE THREAD

**Issue by Sejmou** [JohnBra/vite-web-extension#16]
First of all, thanks for this awesome template, I really like it!

However, I noticed that the line

```css
@tailwind base
```

in `src/pages/content/style.css` causes the [Tailwind preflight](https://tailwindcss.com/docs/preflight) ("CSS reset") to be applied on _any_ page where the content script loads (which by default is any page the user visits).

I assume most users of the extension template, especially beginners, would be confused about the consequences of this: it breaks styling for certain webpages. Most notably, for me this caused links on Google's search results page to become black instead of blue.

In my opinion, it would be preferable to remove this line, or maybe comment it out by default. What's your take on this?

**Comment by JohnBra** [comment]
Hey @Sejmou! Glad you like the template!

I think the most sensible change here would be to apply the content script only to specific pages, rather than having a wildcard in there.

This would be in line with the guidelines by google anyway.

What do you think?

**Comment by Sejmou** [comment]
Yes, I think that would make sense, too!

Honestly, it doesn't matter that much, but maybe adding a note on how this can be customized could be added to the template's README.
