### ISSUE TITLE
Issuw with web_accessible_resources on manifest.dev.json

### ISSUE THREAD

**Issue by moaoa** [JohnBra/vite-web-extension#23]
{
  "action": {
    "default_icon": "public/dev-icon-32.png"
  },
  "icons": {
    "128": "public/dev-icon-128.png"
  },
  "web_accessible_resources": [
    {
      "resources": ["contentStyle.css", "dev-icon-128.png", "dev-icon-32.png"],
      "matches": [] 👈 missing property
    }
  ]
}

**Comment by 2hari** [comment]
facing the same (similar) issue.

![image](https://github.com/JohnBra/vite-web-extension/assets/144526301/71ba1dfd-6428-4689-b13f-e70f8aed6abe)

**Comment by moaoa** [comment]
@2hari
You can either add the attribute "matches" to the manifest.dev.json like in my comment or switch to manifest.json instead of manifest.dev.json

**Comment by JohnBra** [comment]
@moaoa and @2hari thanks for opening and discussing this issue.

At what step does this pop up? I.e. build, upload to CWS etc.

**Comment by JohnBra** [comment]
should be fixed with added matches prop on master. Thanks @moaoa
