### ISSUE TITLE
Popup only shows for `yarn build`

### ISSUE THREAD

**Issue by skube** [JohnBra/vite-web-extension#27]
I probably don't understand fully, but I notice the Popup doesn't appear if one uses `yarn dev`. Rather, you need to `yarn build` to see the Popup in action (i.e. clicking the icon on the toolbar).

Is this intentional?

**Comment by JohnBra** [comment]
@hoffination thanks for finding this! 💪 Would you mind opening a PR with a ref to this issue? Happy to merge it, otherwise I can add the fix when I find the time.
