### ISSUE TITLE
How to specify Web Accessible Script in `web_accessible_resources`?

### ISSUE THREAD

**Issue by skube** [JohnBra/vite-web-extension#28]
My use-case requires a script to be web accessible. This is neither a content script nor a background script. Normally, I would simply list the script in the `manifest.json`:
```json
  "web_accessible_resources": [
    {
      "resources": ["some-accessible-script.js"],
```

How does one accomplish this with this boilerplate?

**Comment by JohnBra** [comment]
Hi @skube, I think what you are looking for is the [scripting API](https://developer.chrome.com/docs/extensions/reference/api/scripting#description).

The boilerplate is just a convenience thing to enable react + tailwind and generate your JS files + manifest. It shouldn't be any different from your standard way of implementing Chrome Extension.

**Comment by skube** [comment]
Thanks @JohnBra. I guess I'm a little confused how to generate the `some-accessible-script.js` from a `.ts` file? Or I just create the `.js` "outside" of the boilerplate system?
