### ISSUE TITLE
For vite version 4 and up use "@crxjs/vite-plugin": "^2.0.0-beta.23",

### ISSUE THREAD

**Issue by Mindaugas3** [JohnBra/vite-web-extension#30]
Some version incompatibility with newer versions of Vite, such as 4.5.2.

Generally, i've been playing around with this boilerplate (with Material UI instead of the default tailwind CSS). Pretty good!

**Comment by Mindaugas3** [comment]
Also injecting tailwind in content will break some pages (including GitLab and Gmail) so i had to remove the import

**Comment by stevenirby** [comment]
> Also injecting tailwind in content will break some pages (including GitLab and Gmail) so i had to remove the import

I ran into the same issue. Not sure what the best work around is without heavily modifying things.

**Comment by Mindaugas3** [comment]
just remove the css import from content scripts index.tsx

**Comment by JohnBra** [comment]
@stevenirby & @Mindaugas3  You could try to give the tailwind stuff a prefix (see [docs](https://tailwindcss.com/docs/configuration#prefix)). I think this might solve your problem

**Comment by stevenirby** [comment]
I figured this out eventually. I wasn't injecting things into the shadow dom correctly.
