### ISSUE TITLE
not working with shadcn

### ISSUE THREAD

**Issue by vinodhum** [JohnBra/vite-web-extension#39]
I am not able to setup shadcn, any idea what am I missing ?
went through the documentation but its not exact fit for vitejs and tried adding path as per  https://ui.shadcn.com/docs/installation/vite but still not working.

✔ Preflight checks.
✔ Verifying framework. Found Vite.
✔ Validating Tailwind CSS.
✖ Validating import alias.

No import alias found in your tsconfig.json file.

tsconfig.json 

```
 "paths": {
      "@/*": ["src/*"],
      "@src/*": ["src/*"],
      "@assets/*": ["src/assets/*"],
      "@pages/*": ["src/pages/*"]
    }
```

**Comment by JohnBra** [comment]
Hi @vinodhum

I'm unfamiliar with shadcn, but after a quick skim of the docs it looks like you can follow these steps to get it set up with vite: [https://ui.shadcn.com/docs/installation/vite#edit-tsconfigjson-file](https://ui.shadcn.com/docs/installation/vite#edit-tsconfigjson-file)

Closing as this isn't an issue with the repo.
