### ISSUE TITLE
Does this template support Mozilla Firefox?

### ISSUE THREAD

**Issue by dim0147** [JohnBra/vite-web-extension#4]
Hi, can I ask does this template support Mozilla Firefox extension?

**Comment by JohnBra** [comment]
Hi @dim0147,

No, as stated in the README this template doesn't currently support Firefox.
Firefox doesn't support manifest v3 and Chrome doesn't allow any new extensions under v3. Once Firefox supports manifest v3 this template will support it Firefox as well.

Read more here: [https://github.com/JohnBra/vite-web-extension#intro-](https://github.com/JohnBra/vite-web-extension#intro-)

**Comment by vhermecz** [comment]
Sounds like Firefox reached v3 general availability a few weeks ago.
https://blog.mozilla.org/addons/2022/11/17/manifest-v3-signing-available-november-21-on-firefox-nightly/
