### ISSUE TITLE
Image not working

### ISSUE THREAD

**Issue by sumonroytony** [JohnBra/vite-web-extension#51]
Hello, can you please tell me how to use public folder image? I tried "/image.jpg" , "public/image.jpg", "/public/image.jpg" but nothing works.

**Comment by JohnBra** [comment]
A few different ways to go about it, depending on where you want to import it.

Link: [https://stackoverflow.com/questions/11804332/insert-an-image-in-chrome-extension](https://stackoverflow.com/questions/11804332/insert-an-image-in-chrome-extension)

For this repo: Files in the public folder will be in the root directory of the dist folders. Your first "/image.jpg" try should work, given you don't import it as an asset in your react files. I.e. just use it as the `src` in the image tag.
