### ISSUE TITLE
Is it possible to make popup "pop out"? 

### ISSUE THREAD

**Issue by henrychea** [JohnBra/vite-web-extension#7]
You can see this behavior with [Bitwarden's plugin here](https://chrome.google.com/webstore/detail/bitwarden-free-password-m/nngceckbapebfimnlniiiahkandclblb). So I'm wondering how I can implement the same feature. Sorry, I'm not very familiar with Vite and configuring chrome extensions ☹️

**Comment by JohnBra** [comment]
Hey @henrychea, thanks for opening the issue.

I'm not exactly sure what you mean by "pop out". The popup is fixed to the Extension Icon. I think what you are looking for is something like this: https://stackoverflow.com/questions/48222950/chrome-extension-in-a-fully-detached-popup

You basically have to create a popout window with scripting.
